Update conventional_commits_style_commit-msg

diff --git a/conventional_commits_style_commit-msg b/conventional_commits_style_commit-msg
--- a/conventional_commits_style_commit-msg
+++ b/conventional_commits_style_commit-msg
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 branch="$(git rev-parse --abbrev-ref HEAD)";
-commit_regex='((CDW-)([1-9][0-9])|((feat|fix|chore|refactor|style|test|docs)(((\w{0,15})))?))(:.\S.*)';
+commit_regex='((CDW\-)([1-9][0-9]*)|((feat|fix|chore|refactor|style|test|docs)(\((\w{0,15})\))?))(\:.*\S.*)';
 error_msg="Aborting commit. Your commit message format is invalid, please check the references."
 commit_message="$1";
 reference_msg="
@@ -34,10 +34,10 @@ feat: add hat wobble
 
 "
 
-if ! grep -iqE "$commit_regex" <<<"${commit_message}"; then
+if ! grep -qE "$commit_regex" "$1"; then
 echo "$reference_msg"
-echo "$error_msg" >&2
-exit 1
+    echo -e "$error_msg" >&2
+    exit 1
 fi
 
 if [ "$branch" = "master" ]; then
